# Generated by Django 5.0.2 on 2024-04-16 02:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0002_ingredient_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="unit",
        ),
    ]
