# Generated by Django 5.0.2 on 2024-04-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0004_recipehadingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                choices=[("u", "units"), ("kg", "kg"), ("l", "liters")],
                default="u",
                max_length=2,
            ),
        ),
    ]
