# Generated by Django 5.0.2 on 2024-05-23 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0006_useractivity"),
        ("recipe", "0002_recipe_cuisine_recipe_number_of_portions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipehadingredient",
            name="recipe_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipe.recipe"
            ),
        ),
    ]
